### ISSUE TITLE
how to use the operations in c++ file op.cpp?

### ISSUE THREAD

**Issue by ifgovh** [norse/norse#187]
I am wondering how can I import the operations in op.cpp to accelerate the process?

**Comment by Jegp** [comment]
Thanks for getting in touch @ifgovh! The C++ code is right now limited to LIF and SuperSpike dynamics (it's something we're working on). Unfortunately, we encountered a bug for MAC (#184) that lead us to temporarily disable the C++ optimization. 

While we fix it, you can definitely run it yourself. One way is to look at the past (somewhat hacky, but functional) solution for the SuperSpike threshold function: 
https://github.com/norse/norse/blob/db79ee7f4c2486c7b7af6787a4d8cd60c06241c9/norse/torch/functional/threshold.py#L8

Did that answer your question?

**Comment by ifgovh** [comment]
Thank you @Jegp ! It answered my question. BTW, I found norse uses nn.Linear to calculate wz (norse/torch/functional/lsnn.py, line 122). It is ok but normally spiking neurons do not connect to themself.

**Comment by Jegp** [comment]
Glad I could help! I hope we have a fix for it out soon.

Regarding the `lsnn_step`, it does indeed include linear and recurrent  connectivity. That's intentional, and there is a non-linear, non-weighted version in https://github.com/norse/norse/blob/master/norse/torch/functional/lsnn.py#L202

You're always welcome to join us on [Discord](https://discord.gg/7fGN359) or use the GitHub discussion page in this repo if you have any questions or would like some advice.
