### ISSUE TITLE
Unable to install norse successfully

### ISSUE THREAD

**Issue by Dola47** [norse/norse#197]
**Describe the bug**
I tried to install norse normally using: `pip install norse`. However, I encountered a lot of errors I attached a screenshot for that.

**Screenshots**
![Error1](https://user-images.githubusercontent.com/45386621/114012958-47e25200-9867-11eb-82f1-21ce350d3ca1.PNG)
![Error2](https://user-images.githubusercontent.com/45386621/114012962-49ac1580-9867-11eb-9c16-5720004c8725.PNG)

Please let me know if anyone faced such an error or it is only specific to me, and if there is anyway to overcome it.

Thanks in advance.

**Comment by cpehle** [comment]
This is an issue with the gcc version that is installed on your system, it doesn't support the C++-14 standard. This is also what the warning and error in your second screen shot is about.

**Comment by Dola47** [comment]
@cpehle  Thanks a lot for your comment.

I checked my GCC it is 4.8.5.

Any ideas on how to upgrade it only to my local environment? I am using CentOS Linux release 7.8.2003.

**Comment by cpehle** [comment]
Sure one way of doing so would be to use miniconda and install a more recent version of gcc in a conda environment, generally speaking that is one good way of dealing with python dependencies, because the environment then lets you reproduce the setup. Here is one package that I found which should install gcc-9 in your environment: https://anaconda.org/conda-forge/gcc_linux-64. Here is the installer page for miniconda: https://docs.conda.io/en/latest/miniconda.html

**Comment by cpehle** [comment]
Other than that your sysadmin should be able to help you, on CentOS type systems alternative compilers are often installed as modules that can be loaded, as in 
```
module load gcc/8.3.0
```
(for example).

**Comment by Dola47** [comment]
@cpehle  Really thanks a lot for your quick replies.

Unfortunately, I am not using a conda environment, I am using a Python virtual environment. 

In this case, I agree that it is a better idea to reach my sysadmin.
