### ISSUE TITLE
Implementation: superspike method

### ISSUE THREAD

**Issue by Pugavkomm** [norse/norse#282]
Hello. I would like to clarify a little more the difference between the superspike method and the superspike derivative. That is, was only equation 3 from the [article](https://arxiv.org/abs/1705.11146v2) implementing? If so, how could I extend to the method itself. In other words, what is the learning difference between the Superspike method and the gradient function that is implemented in the library?

_Originally posted by @Pugavkomm in https://github.com/norse/norse/discussions/168#discussioncomment-1842645_

**Comment by cpehle** [comment]
The super spike method itself uses an "online" computation to calculate gradients, you can see an example of an implementation here: https://electronicvisions.github.io/documentation-brainscales2/brainscales2-demos/2-superspike.html. This is distinct from using a "surrogate" or pseudo-derivative to compute gradients.

**Comment by Pugavkomm** [comment]
I understood it. I was just interested in the derivative. The type of the derivative is set as in equation 3 in the article, which you also stuck in the documentation. Is that so or not?

**Comment by Jegp** [comment]
The existing implementation is indeed from section 3.3.2 in the Zenke paper.

If you don't mind, I would suggest closing the issue since it's not strictly an *issue* with the library. I hope you don't mistake this to mean that we don't wish to discuss this :-) The discussion here on GitHub or our Discord server is a great place to continue the conversation.
