### ISSUE TITLE
Investigate Changing Input Current Delay and Integration

### ISSUE THREAD

**Issue by cpehle** [norse/norse#325]
LeonardBo brought up the following issue to our attention here (https://github.com/norse/norse/discussions/318):

> Input currently seems to affect the voltage at the 2nd timestep at the earliest.
> 
> I have notic,ed the reocurring pattern in my network that every LIF layer seemed to halt the forward progression of spikes in the network for a few timesteps. It didn't seem unnatural at first since the neuron's threshold may need several time steps to be overcome. However, even with very small thresholds the problem persisted so I dove depp into the code for the LIF step.
> 
> What I found is that in the very first timestep, the current input doesn't influence the voltage at all, as seen [here](https://github.com/norse/norse/blob/73d7c53cf0200fd1f1042e347102ebb09b630072/norse/csrc/lif.cpp#L28) -> it'll only affect the next time step's state.i. Now naturally, this effect will accumulate over several LIF layers; a reasonably sized network of 5 LIF activation layers will, at the very least, need 6 time steps to produce any meaningful output at all.
>
> Now since this is a hopefully intentional design decision I didn't open an issue but wanted to discuss it here. I can see that purely from the underlying ODE's point of view this might be fine. However, from a practical point of view that creates an unnecessary inefficient spiking behaviour.
>
> It seems to me, you might as well calculate i_new first and use that to update the neuron's voltage in [Line 16](https://github.com/norse/norse/blob/73d7c53cf0200fd1f1042e347102ebb09b630072/norse/csrc/lif.cpp#L16) instead of the old state's i. There might also be some other options to have the current input directly influence the current voltage. I might have missed some theoretical background justifying this, but it looks like that may fit the spiking model, too. Does that seem reasonable to you?

This issue is here to track potential solutions, including changing the behaviour outright. We need to think about whether we should address this concurrently with a move to the planned ODE integration interface.

**Comment by Jegp** [comment]
I'm not sure I follow the logic here. I completely understand that the delay is "annoying" from a practical point of view. But it's also an inherent property of SNNs that they simply do not propagate signals immediately.

I'm wondering whether this is A) something Norse should consider and, if so, B) something we can include in the synapse dynamics. I'm saying that because we recently had talks about separating synapse and cell dynamics. That could be one way of getting about this issue, because we could have models without any form of delay.

**Comment by cpehle** [comment]
The current behavior was mostly motivated to be consistent with the current recurrent implementation, where a delay of 1 timestep seems sensible. For the forward integration that is less relevant and can lead to undesirably long delays. I think doing this change would probably be less work than doing a wholesale migration to a synapse neuron dynamics split.

**Comment by LennardBo** [comment]
To some degree I understand @Jegp 's viewpoint that this behaviour is intended to simulate the neuron's dynamics. That's why I introduced this issue as a discussion rather than an issue.

After reading the merge request I understand this might ahve been mostly motivated by the recurrent layers and their consistency. However, for straight feed-forward networks this change is really important. Many SNN papers such as [this](https://www.semanticscholar.org/paper/Training-Energy-Efficient-Deep-Spiking-Neural-with-Datta-Kundu/3fc62a9129681864c8db69eb8482a03cd1aa1746) and [this](https://www.semanticscholar.org/paper/DIET-SNN%3A-Direct-Input-Encoding-With-Leakage-and-in-Rathi-Roy/52f0a2d68c39342230be7c9ab46dea71738949a9) mainly concern themselves with a short sequence length to reduce computational overhead. With the current implementation, the input lag actually makes implementing a comparably fast network impossible.

I'm very thankful for @cpehle to take my topic to heart and writing this update. I'm looking forward to future versions of Norse containg these changes.

**Comment by cpehle** [comment]
There is one additional concern that I haven't mentioned yet and that is compatibility with the "adjoint code", I admittedly have not fully investigated this, as there the order also affects the correct order in which the "backward dynamics" needs to be implemented.

**Comment by Jegp** [comment]
Thanks for your understanding @LennardBo. I'm grateful you brought it up, and I strongly believe we should act on the shorter term.

As @cpehle mentioned, we've been thinking about ways to progress Norse without loss of generality. Your issue is (unfortunately) touching on a longer discussion that I would like to think carefully about, hence the skepticism. One of the reasons Norse is attractive/viable, I believe, is because we're serious about stability and correctness. But @cpehle correctly acted on this and I'm sure we can wrap up the short-term matters quickly.

So, thanks again for bringing this to our attention! :-) I think we should try to move the discussion about integration out in the open and see how we can proceed there. Inputs are deeply appreciated.
