### ISSUE TITLE
Support for torch.nn.Sequential

### ISSUE THREAD

**Issue by cpehle** [norse/norse#95]
torch.nn.Sequential is a very convenient wrapper for creating feed forward networks by stacking layers. By implementing the integration layer by layer and lifting non-temporal operations like convolutions by applying them pointwise in time, we can reuse the torch.nn.Sequential module without any modifications.

```python
torch.nn.Sequential([
       norse.torch.module.Lift(torch.nn.Conv2d(...)),
       norse.torch.module.LIFFeedForwardLayer(...),
       ...
])
```

**Comment by Jegp** [comment]
There's still a problem here because of the state unfortunately. It works *if* there is only one spiking layer, *and* if it at the end. In all other cases the returned tuple is a problem for both the LIFLayer (which can be fixed) and the native Torch modules (who are not used to dealing with states).

I think there are four ways around this
1. Either create our own sequential layer, that just checks whether the output of a layer is a tuple and deals with it there, or
2. Fix Norse Layers to cope with inputs that might be tuples
3. Refactor the state of the neuron cells to not be a part of the returned value
4. Attach neuron state to the tensors

I prefer 1 over 2 to offer compatibility with PyTorch code. 3 is not a good idea, and 4 is pretty detrimental to performance I guess. But it should work in principle.

**Comment by Jegp** [comment]
Here's one suggestion how such a module could look like: https://github.com/norse/norse/commit/184700c7d639b7bdb8498899b5b4313ea0186939

**Comment by cpehle** [comment]
The slightly hacky way I dealt with that is by letting Lift only consider the first input of an input tuple. That should make composing Norse modules and non-temporal Pytorch Modules possible. You are right that this doesn’t allow Norse modules to be composed directly, we could fix that by optionally dropping the last returned state in all *Layers.

**Comment by Jegp** [comment]
Yeah, that could also work actually. The problem being that we'd then depend on the Lift module for *all* native PyTorch modules. In principle, I'd be fine with that, but we could be in trouble for some type of convolutions for instance.

How would dropping the last state work then? Would we have a `.state` variable accessible if one wanted to retain the state going forward? I can see that working, but wouldn't that also break with the nice stateless principles so far?
